### PR TITLE
added group/spellbook classes and encapsulated stats

### PR DESCRIPTION
**Pull request by syc0n**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/CUModSquad/cu-core/pull/14" target="_blank">ReviewNinja

**Comment by saddieeiddas** [comment]
@syc0n would you be able to do a rebuild with latest build-tools. Have fixed a few issues, that should hopefully work better now.

**Comment by syc0n** [comment]
@saddieeiddas merged and done

**Comment by codecorsair** [comment]
Can you resolve conflicts and then resubmit the PR to CUModSquad's fork? https://github.com/CUModSquad/cu-core

**Pull request closed without merging**
